apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
    name: "mnsocialtraderks"
    labels:
        app: "mnsocialtraderks"
spec:
    type: ClusterIP
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "mnsocialtraderks"
=======
    name: devopsimage
spec:
    type: LoadBalancer
    ports:
    - port: 3000 
    selector:
        app: devopsimage
>>>>>>> 369efd5dbacc01ae2ef4af47af19fe910c930279
